// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airconditiondata.proto

package com.zzx.protoClasses;

public final class AirconditionDataProto {
  private AirconditionDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AirconditionDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzx.protoClasses.AirconditionData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msg_id = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required int32 msg_id = 1;</code>
     */
    int getMsgId();
  }
  /**
   * Protobuf type {@code com.zzx.protoClasses.AirconditionData}
   */
  public  static final class AirconditionData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzx.protoClasses.AirconditionData)
      AirconditionDataOrBuilder {
    // Use AirconditionData.newBuilder() to construct.
    private AirconditionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AirconditionData() {
      msgId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AirconditionData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzx.protoClasses.AirconditionDataProto.AirconditionData.class, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>required int32 msg_id = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msg_id = 1;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzx.protoClasses.AirconditionDataProto.AirconditionData)) {
        return super.equals(obj);
      }
      com.zzx.protoClasses.AirconditionDataProto.AirconditionData other = (com.zzx.protoClasses.AirconditionDataProto.AirconditionData) obj;

      boolean result = true;
      result = result && (hasMsgId() == other.hasMsgId());
      if (hasMsgId()) {
        result = result && (getMsgId()
            == other.getMsgId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzx.protoClasses.AirconditionDataProto.AirconditionData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzx.protoClasses.AirconditionData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzx.protoClasses.AirconditionData)
        com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzx.protoClasses.AirconditionDataProto.AirconditionData.class, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder.class);
      }

      // Construct using com.zzx.protoClasses.AirconditionDataProto.AirconditionData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionData_descriptor;
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDefaultInstanceForType() {
        return com.zzx.protoClasses.AirconditionDataProto.AirconditionData.getDefaultInstance();
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData build() {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData buildPartial() {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionData result = new com.zzx.protoClasses.AirconditionDataProto.AirconditionData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzx.protoClasses.AirconditionDataProto.AirconditionData) {
          return mergeFrom((com.zzx.protoClasses.AirconditionDataProto.AirconditionData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzx.protoClasses.AirconditionDataProto.AirconditionData other) {
        if (other == com.zzx.protoClasses.AirconditionDataProto.AirconditionData.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzx.protoClasses.AirconditionDataProto.AirconditionData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgId_ ;
      /**
       * <code>required int32 msg_id = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msg_id = 1;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required int32 msg_id = 1;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzx.protoClasses.AirconditionData)
    }

    // @@protoc_insertion_point(class_scope:com.zzx.protoClasses.AirconditionData)
    private static final com.zzx.protoClasses.AirconditionDataProto.AirconditionData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzx.protoClasses.AirconditionDataProto.AirconditionData();
    }

    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AirconditionData>
        PARSER = new com.google.protobuf.AbstractParser<AirconditionData>() {
      public AirconditionData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AirconditionData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AirconditionData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AirconditionData> getParserForType() {
      return PARSER;
    }

    public com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AirconditionDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzx.protoClasses.AirconditionDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData> 
        getDataListList();
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDataList(int index);
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    int getDataListCount();
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    java.util.List<? extends com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder> 
        getDataListOrBuilderList();
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder getDataListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zzx.protoClasses.AirconditionDataList}
   */
  public  static final class AirconditionDataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzx.protoClasses.AirconditionDataList)
      AirconditionDataListOrBuilder {
    // Use AirconditionDataList.newBuilder() to construct.
    private AirconditionDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AirconditionDataList() {
      dataList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AirconditionDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataList_ = new java.util.ArrayList<com.zzx.protoClasses.AirconditionDataProto.AirconditionData>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataList_.add(
                  input.readMessage(com.zzx.protoClasses.AirconditionDataProto.AirconditionData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataList_ = java.util.Collections.unmodifiableList(dataList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.class, com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.Builder.class);
    }

    public static final int DATA_LIST_FIELD_NUMBER = 1;
    private java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData> dataList_;
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    public java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData> getDataListList() {
      return dataList_;
    }
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    public java.util.List<? extends com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder> 
        getDataListOrBuilderList() {
      return dataList_;
    }
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    public int getDataListCount() {
      return dataList_.size();
    }
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    public com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDataList(int index) {
      return dataList_.get(index);
    }
    /**
     * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
     */
    public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder getDataListOrBuilder(
        int index) {
      return dataList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDataListCount(); i++) {
        if (!getDataList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dataList_.size(); i++) {
        output.writeMessage(1, dataList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList)) {
        return super.equals(obj);
      }
      com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList other = (com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList) obj;

      boolean result = true;
      result = result && getDataListList()
          .equals(other.getDataListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataListCount() > 0) {
        hash = (37 * hash) + DATA_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getDataListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzx.protoClasses.AirconditionDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzx.protoClasses.AirconditionDataList)
        com.zzx.protoClasses.AirconditionDataProto.AirconditionDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.class, com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.Builder.class);
      }

      // Construct using com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataListBuilder_ == null) {
          dataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzx.protoClasses.AirconditionDataProto.internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor;
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList getDefaultInstanceForType() {
        return com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.getDefaultInstance();
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList build() {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList buildPartial() {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList result = new com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList(this);
        int from_bitField0_ = bitField0_;
        if (dataListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dataList_ = java.util.Collections.unmodifiableList(dataList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataList_ = dataList_;
        } else {
          result.dataList_ = dataListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList) {
          return mergeFrom((com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList other) {
        if (other == com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList.getDefaultInstance()) return this;
        if (dataListBuilder_ == null) {
          if (!other.dataList_.isEmpty()) {
            if (dataList_.isEmpty()) {
              dataList_ = other.dataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataListIsMutable();
              dataList_.addAll(other.dataList_);
            }
            onChanged();
          }
        } else {
          if (!other.dataList_.isEmpty()) {
            if (dataListBuilder_.isEmpty()) {
              dataListBuilder_.dispose();
              dataListBuilder_ = null;
              dataList_ = other.dataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataListFieldBuilder() : null;
            } else {
              dataListBuilder_.addAllMessages(other.dataList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataListCount(); i++) {
          if (!getDataList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData> dataList_ =
        java.util.Collections.emptyList();
      private void ensureDataListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataList_ = new java.util.ArrayList<com.zzx.protoClasses.AirconditionDataProto.AirconditionData>(dataList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zzx.protoClasses.AirconditionDataProto.AirconditionData, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder, com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder> dataListBuilder_;

      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData> getDataListList() {
        if (dataListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataList_);
        } else {
          return dataListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public int getDataListCount() {
        if (dataListBuilder_ == null) {
          return dataList_.size();
        } else {
          return dataListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData getDataList(int index) {
        if (dataListBuilder_ == null) {
          return dataList_.get(index);
        } else {
          return dataListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder setDataList(
          int index, com.zzx.protoClasses.AirconditionDataProto.AirconditionData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.set(index, value);
          onChanged();
        } else {
          dataListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder setDataList(
          int index, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder addDataList(com.zzx.protoClasses.AirconditionDataProto.AirconditionData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.add(value);
          onChanged();
        } else {
          dataListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder addDataList(
          int index, com.zzx.protoClasses.AirconditionDataProto.AirconditionData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.add(index, value);
          onChanged();
        } else {
          dataListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder addDataList(
          com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.add(builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder addDataList(
          int index, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder addAllDataList(
          java.lang.Iterable<? extends com.zzx.protoClasses.AirconditionDataProto.AirconditionData> values) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataList_);
          onChanged();
        } else {
          dataListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder clearDataList() {
        if (dataListBuilder_ == null) {
          dataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public Builder removeDataList(int index) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.remove(index);
          onChanged();
        } else {
          dataListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder getDataListBuilder(
          int index) {
        return getDataListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder getDataListOrBuilder(
          int index) {
        if (dataListBuilder_ == null) {
          return dataList_.get(index);  } else {
          return dataListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public java.util.List<? extends com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder> 
           getDataListOrBuilderList() {
        if (dataListBuilder_ != null) {
          return dataListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataList_);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder addDataListBuilder() {
        return getDataListFieldBuilder().addBuilder(
            com.zzx.protoClasses.AirconditionDataProto.AirconditionData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder addDataListBuilder(
          int index) {
        return getDataListFieldBuilder().addBuilder(
            index, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzx.protoClasses.AirconditionData data_list = 1;</code>
       */
      public java.util.List<com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder> 
           getDataListBuilderList() {
        return getDataListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zzx.protoClasses.AirconditionDataProto.AirconditionData, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder, com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder> 
          getDataListFieldBuilder() {
        if (dataListBuilder_ == null) {
          dataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zzx.protoClasses.AirconditionDataProto.AirconditionData, com.zzx.protoClasses.AirconditionDataProto.AirconditionData.Builder, com.zzx.protoClasses.AirconditionDataProto.AirconditionDataOrBuilder>(
                  dataList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dataList_ = null;
        }
        return dataListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzx.protoClasses.AirconditionDataList)
    }

    // @@protoc_insertion_point(class_scope:com.zzx.protoClasses.AirconditionDataList)
    private static final com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList();
    }

    public static com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AirconditionDataList>
        PARSER = new com.google.protobuf.AbstractParser<AirconditionDataList>() {
      public AirconditionDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AirconditionDataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AirconditionDataList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AirconditionDataList> getParserForType() {
      return PARSER;
    }

    public com.zzx.protoClasses.AirconditionDataProto.AirconditionDataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzx_protoClasses_AirconditionData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzx_protoClasses_AirconditionData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzx_protoClasses_AirconditionDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026airconditiondata.proto\022\024com.zzx.protoC" +
      "lasses\"\"\n\020AirconditionData\022\016\n\006msg_id\030\001 \002" +
      "(\005\"Q\n\024AirconditionDataList\0229\n\tdata_list\030" +
      "\001 \003(\0132&.com.zzx.protoClasses.Airconditio" +
      "nDataB-\n\024com.zzx.protoClassesB\025Aircondit" +
      "ionDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzx_protoClasses_AirconditionData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzx_protoClasses_AirconditionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzx_protoClasses_AirconditionData_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zzx_protoClasses_AirconditionDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzx_protoClasses_AirconditionDataList_descriptor,
        new java.lang.String[] { "DataList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
