// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbdata.proto

package com.zzx.protoClasses;

public final class DbDataProto {
  private DbDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DbDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzx.protoClasses.DbData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 gui_id = 1;</code>
     */
    boolean hasGuiId();
    /**
     * <code>required int32 gui_id = 1;</code>
     */
    int getGuiId();

    /**
     * <code>required int32 device_id = 2;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required int32 device_id = 2;</code>
     */
    int getDeviceId();

    /**
     * <code>required string device_name = 3;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>required string device_name = 3;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>required string device_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>required string device_pos = 4;</code>
     */
    boolean hasDevicePos();
    /**
     * <code>required string device_pos = 4;</code>
     */
    java.lang.String getDevicePos();
    /**
     * <code>required string device_pos = 4;</code>
     */
    com.google.protobuf.ByteString
        getDevicePosBytes();

    /**
     * <code>required string device_ip = 5;</code>
     */
    boolean hasDeviceIp();
    /**
     * <code>required string device_ip = 5;</code>
     */
    java.lang.String getDeviceIp();
    /**
     * <code>required string device_ip = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIpBytes();

    /**
     * <code>required string module = 6;</code>
     */
    boolean hasModule();
    /**
     * <code>required string module = 6;</code>
     */
    java.lang.String getModule();
    /**
     * <code>required string module = 6;</code>
     */
    com.google.protobuf.ByteString
        getModuleBytes();
  }
  /**
   * Protobuf type {@code com.zzx.protoClasses.DbData}
   */
  public  static final class DbData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzx.protoClasses.DbData)
      DbDataOrBuilder {
    // Use DbData.newBuilder() to construct.
    private DbData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DbData() {
      guiId_ = 0;
      deviceId_ = 0;
      deviceName_ = "";
      devicePos_ = "";
      deviceIp_ = "";
      module_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DbData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              guiId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deviceId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              deviceName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              devicePos_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              deviceIp_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              module_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzx.protoClasses.DbDataProto.DbData.class, com.zzx.protoClasses.DbDataProto.DbData.Builder.class);
    }

    private int bitField0_;
    public static final int GUI_ID_FIELD_NUMBER = 1;
    private int guiId_;
    /**
     * <code>required int32 gui_id = 1;</code>
     */
    public boolean hasGuiId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 gui_id = 1;</code>
     */
    public int getGuiId() {
      return guiId_;
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private int deviceId_;
    /**
     * <code>required int32 device_id = 2;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 device_id = 2;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object deviceName_;
    /**
     * <code>required string device_name = 3;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string device_name = 3;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_POS_FIELD_NUMBER = 4;
    private volatile java.lang.Object devicePos_;
    /**
     * <code>required string device_pos = 4;</code>
     */
    public boolean hasDevicePos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string device_pos = 4;</code>
     */
    public java.lang.String getDevicePos() {
      java.lang.Object ref = devicePos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          devicePos_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_pos = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDevicePosBytes() {
      java.lang.Object ref = devicePos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devicePos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object deviceIp_;
    /**
     * <code>required string device_ip = 5;</code>
     */
    public boolean hasDeviceIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string device_ip = 5;</code>
     */
    public java.lang.String getDeviceIp() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_ip = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULE_FIELD_NUMBER = 6;
    private volatile java.lang.Object module_;
    /**
     * <code>required string module = 6;</code>
     */
    public boolean hasModule() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string module = 6;</code>
     */
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          module_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string module = 6;</code>
     */
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGuiId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevicePos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, guiId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, deviceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, devicePos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, module_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, guiId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, deviceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, devicePos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, module_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzx.protoClasses.DbDataProto.DbData)) {
        return super.equals(obj);
      }
      com.zzx.protoClasses.DbDataProto.DbData other = (com.zzx.protoClasses.DbDataProto.DbData) obj;

      boolean result = true;
      result = result && (hasGuiId() == other.hasGuiId());
      if (hasGuiId()) {
        result = result && (getGuiId()
            == other.getGuiId());
      }
      result = result && (hasDeviceId() == other.hasDeviceId());
      if (hasDeviceId()) {
        result = result && (getDeviceId()
            == other.getDeviceId());
      }
      result = result && (hasDeviceName() == other.hasDeviceName());
      if (hasDeviceName()) {
        result = result && getDeviceName()
            .equals(other.getDeviceName());
      }
      result = result && (hasDevicePos() == other.hasDevicePos());
      if (hasDevicePos()) {
        result = result && getDevicePos()
            .equals(other.getDevicePos());
      }
      result = result && (hasDeviceIp() == other.hasDeviceIp());
      if (hasDeviceIp()) {
        result = result && getDeviceIp()
            .equals(other.getDeviceIp());
      }
      result = result && (hasModule() == other.hasModule());
      if (hasModule()) {
        result = result && getModule()
            .equals(other.getModule());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGuiId()) {
        hash = (37 * hash) + GUI_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGuiId();
      }
      if (hasDeviceId()) {
        hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceId();
      }
      if (hasDeviceName()) {
        hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceName().hashCode();
      }
      if (hasDevicePos()) {
        hash = (37 * hash) + DEVICE_POS_FIELD_NUMBER;
        hash = (53 * hash) + getDevicePos().hashCode();
      }
      if (hasDeviceIp()) {
        hash = (37 * hash) + DEVICE_IP_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceIp().hashCode();
      }
      if (hasModule()) {
        hash = (37 * hash) + MODULE_FIELD_NUMBER;
        hash = (53 * hash) + getModule().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzx.protoClasses.DbDataProto.DbData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzx.protoClasses.DbData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzx.protoClasses.DbData)
        com.zzx.protoClasses.DbDataProto.DbDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzx.protoClasses.DbDataProto.DbData.class, com.zzx.protoClasses.DbDataProto.DbData.Builder.class);
      }

      // Construct using com.zzx.protoClasses.DbDataProto.DbData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        guiId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        devicePos_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        module_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbData_descriptor;
      }

      public com.zzx.protoClasses.DbDataProto.DbData getDefaultInstanceForType() {
        return com.zzx.protoClasses.DbDataProto.DbData.getDefaultInstance();
      }

      public com.zzx.protoClasses.DbDataProto.DbData build() {
        com.zzx.protoClasses.DbDataProto.DbData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzx.protoClasses.DbDataProto.DbData buildPartial() {
        com.zzx.protoClasses.DbDataProto.DbData result = new com.zzx.protoClasses.DbDataProto.DbData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guiId_ = guiId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.devicePos_ = devicePos_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceIp_ = deviceIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.module_ = module_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzx.protoClasses.DbDataProto.DbData) {
          return mergeFrom((com.zzx.protoClasses.DbDataProto.DbData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzx.protoClasses.DbDataProto.DbData other) {
        if (other == com.zzx.protoClasses.DbDataProto.DbData.getDefaultInstance()) return this;
        if (other.hasGuiId()) {
          setGuiId(other.getGuiId());
        }
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000004;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasDevicePos()) {
          bitField0_ |= 0x00000008;
          devicePos_ = other.devicePos_;
          onChanged();
        }
        if (other.hasDeviceIp()) {
          bitField0_ |= 0x00000010;
          deviceIp_ = other.deviceIp_;
          onChanged();
        }
        if (other.hasModule()) {
          bitField0_ |= 0x00000020;
          module_ = other.module_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGuiId()) {
          return false;
        }
        if (!hasDeviceId()) {
          return false;
        }
        if (!hasDeviceName()) {
          return false;
        }
        if (!hasDevicePos()) {
          return false;
        }
        if (!hasDeviceIp()) {
          return false;
        }
        if (!hasModule()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzx.protoClasses.DbDataProto.DbData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzx.protoClasses.DbDataProto.DbData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int guiId_ ;
      /**
       * <code>required int32 gui_id = 1;</code>
       */
      public boolean hasGuiId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 gui_id = 1;</code>
       */
      public int getGuiId() {
        return guiId_;
      }
      /**
       * <code>required int32 gui_id = 1;</code>
       */
      public Builder setGuiId(int value) {
        bitField0_ |= 0x00000001;
        guiId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gui_id = 1;</code>
       */
      public Builder clearGuiId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guiId_ = 0;
        onChanged();
        return this;
      }

      private int deviceId_ ;
      /**
       * <code>required int32 device_id = 2;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 device_id = 2;</code>
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>required int32 device_id = 2;</code>
       */
      public Builder setDeviceId(int value) {
        bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 device_id = 2;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <code>required string device_name = 3;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string device_name = 3;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_name = 3;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_name = 3;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_name = 3;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object devicePos_ = "";
      /**
       * <code>required string device_pos = 4;</code>
       */
      public boolean hasDevicePos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string device_pos = 4;</code>
       */
      public java.lang.String getDevicePos() {
        java.lang.Object ref = devicePos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            devicePos_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_pos = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDevicePosBytes() {
        java.lang.Object ref = devicePos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devicePos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_pos = 4;</code>
       */
      public Builder setDevicePos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        devicePos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_pos = 4;</code>
       */
      public Builder clearDevicePos() {
        bitField0_ = (bitField0_ & ~0x00000008);
        devicePos_ = getDefaultInstance().getDevicePos();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_pos = 4;</code>
       */
      public Builder setDevicePosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        devicePos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceIp_ = "";
      /**
       * <code>required string device_ip = 5;</code>
       */
      public boolean hasDeviceIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string device_ip = 5;</code>
       */
      public java.lang.String getDeviceIp() {
        java.lang.Object ref = deviceIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_ip = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIpBytes() {
        java.lang.Object ref = deviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_ip = 5;</code>
       */
      public Builder setDeviceIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_ip = 5;</code>
       */
      public Builder clearDeviceIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceIp_ = getDefaultInstance().getDeviceIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_ip = 5;</code>
       */
      public Builder setDeviceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object module_ = "";
      /**
       * <code>required string module = 6;</code>
       */
      public boolean hasModule() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string module = 6;</code>
       */
      public java.lang.String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            module_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string module = 6;</code>
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        java.lang.Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string module = 6;</code>
       */
      public Builder setModule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string module = 6;</code>
       */
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000020);
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <code>required string module = 6;</code>
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        module_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzx.protoClasses.DbData)
    }

    // @@protoc_insertion_point(class_scope:com.zzx.protoClasses.DbData)
    private static final com.zzx.protoClasses.DbDataProto.DbData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzx.protoClasses.DbDataProto.DbData();
    }

    public static com.zzx.protoClasses.DbDataProto.DbData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DbData>
        PARSER = new com.google.protobuf.AbstractParser<DbData>() {
      public DbData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DbData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DbData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DbData> getParserForType() {
      return PARSER;
    }

    public com.zzx.protoClasses.DbDataProto.DbData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DbDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzx.protoClasses.DbDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    java.util.List<com.zzx.protoClasses.DbDataProto.DbData> 
        getDataListList();
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    com.zzx.protoClasses.DbDataProto.DbData getDataList(int index);
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    int getDataListCount();
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    java.util.List<? extends com.zzx.protoClasses.DbDataProto.DbDataOrBuilder> 
        getDataListOrBuilderList();
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    com.zzx.protoClasses.DbDataProto.DbDataOrBuilder getDataListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zzx.protoClasses.DbDataList}
   */
  public  static final class DbDataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzx.protoClasses.DbDataList)
      DbDataListOrBuilder {
    // Use DbDataList.newBuilder() to construct.
    private DbDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DbDataList() {
      dataList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DbDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataList_ = new java.util.ArrayList<com.zzx.protoClasses.DbDataProto.DbData>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataList_.add(
                  input.readMessage(com.zzx.protoClasses.DbDataProto.DbData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataList_ = java.util.Collections.unmodifiableList(dataList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbDataList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzx.protoClasses.DbDataProto.DbDataList.class, com.zzx.protoClasses.DbDataProto.DbDataList.Builder.class);
    }

    public static final int DATA_LIST_FIELD_NUMBER = 1;
    private java.util.List<com.zzx.protoClasses.DbDataProto.DbData> dataList_;
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    public java.util.List<com.zzx.protoClasses.DbDataProto.DbData> getDataListList() {
      return dataList_;
    }
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    public java.util.List<? extends com.zzx.protoClasses.DbDataProto.DbDataOrBuilder> 
        getDataListOrBuilderList() {
      return dataList_;
    }
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    public int getDataListCount() {
      return dataList_.size();
    }
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    public com.zzx.protoClasses.DbDataProto.DbData getDataList(int index) {
      return dataList_.get(index);
    }
    /**
     * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
     */
    public com.zzx.protoClasses.DbDataProto.DbDataOrBuilder getDataListOrBuilder(
        int index) {
      return dataList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDataListCount(); i++) {
        if (!getDataList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dataList_.size(); i++) {
        output.writeMessage(1, dataList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzx.protoClasses.DbDataProto.DbDataList)) {
        return super.equals(obj);
      }
      com.zzx.protoClasses.DbDataProto.DbDataList other = (com.zzx.protoClasses.DbDataProto.DbDataList) obj;

      boolean result = true;
      result = result && getDataListList()
          .equals(other.getDataListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataListCount() > 0) {
        hash = (37 * hash) + DATA_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getDataListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzx.protoClasses.DbDataProto.DbDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzx.protoClasses.DbDataProto.DbDataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzx.protoClasses.DbDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzx.protoClasses.DbDataList)
        com.zzx.protoClasses.DbDataProto.DbDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbDataList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzx.protoClasses.DbDataProto.DbDataList.class, com.zzx.protoClasses.DbDataProto.DbDataList.Builder.class);
      }

      // Construct using com.zzx.protoClasses.DbDataProto.DbDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataListBuilder_ == null) {
          dataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzx.protoClasses.DbDataProto.internal_static_com_zzx_protoClasses_DbDataList_descriptor;
      }

      public com.zzx.protoClasses.DbDataProto.DbDataList getDefaultInstanceForType() {
        return com.zzx.protoClasses.DbDataProto.DbDataList.getDefaultInstance();
      }

      public com.zzx.protoClasses.DbDataProto.DbDataList build() {
        com.zzx.protoClasses.DbDataProto.DbDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zzx.protoClasses.DbDataProto.DbDataList buildPartial() {
        com.zzx.protoClasses.DbDataProto.DbDataList result = new com.zzx.protoClasses.DbDataProto.DbDataList(this);
        int from_bitField0_ = bitField0_;
        if (dataListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dataList_ = java.util.Collections.unmodifiableList(dataList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataList_ = dataList_;
        } else {
          result.dataList_ = dataListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzx.protoClasses.DbDataProto.DbDataList) {
          return mergeFrom((com.zzx.protoClasses.DbDataProto.DbDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzx.protoClasses.DbDataProto.DbDataList other) {
        if (other == com.zzx.protoClasses.DbDataProto.DbDataList.getDefaultInstance()) return this;
        if (dataListBuilder_ == null) {
          if (!other.dataList_.isEmpty()) {
            if (dataList_.isEmpty()) {
              dataList_ = other.dataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataListIsMutable();
              dataList_.addAll(other.dataList_);
            }
            onChanged();
          }
        } else {
          if (!other.dataList_.isEmpty()) {
            if (dataListBuilder_.isEmpty()) {
              dataListBuilder_.dispose();
              dataListBuilder_ = null;
              dataList_ = other.dataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataListFieldBuilder() : null;
            } else {
              dataListBuilder_.addAllMessages(other.dataList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataListCount(); i++) {
          if (!getDataList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzx.protoClasses.DbDataProto.DbDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzx.protoClasses.DbDataProto.DbDataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zzx.protoClasses.DbDataProto.DbData> dataList_ =
        java.util.Collections.emptyList();
      private void ensureDataListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataList_ = new java.util.ArrayList<com.zzx.protoClasses.DbDataProto.DbData>(dataList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zzx.protoClasses.DbDataProto.DbData, com.zzx.protoClasses.DbDataProto.DbData.Builder, com.zzx.protoClasses.DbDataProto.DbDataOrBuilder> dataListBuilder_;

      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public java.util.List<com.zzx.protoClasses.DbDataProto.DbData> getDataListList() {
        if (dataListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataList_);
        } else {
          return dataListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public int getDataListCount() {
        if (dataListBuilder_ == null) {
          return dataList_.size();
        } else {
          return dataListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public com.zzx.protoClasses.DbDataProto.DbData getDataList(int index) {
        if (dataListBuilder_ == null) {
          return dataList_.get(index);
        } else {
          return dataListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder setDataList(
          int index, com.zzx.protoClasses.DbDataProto.DbData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.set(index, value);
          onChanged();
        } else {
          dataListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder setDataList(
          int index, com.zzx.protoClasses.DbDataProto.DbData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder addDataList(com.zzx.protoClasses.DbDataProto.DbData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.add(value);
          onChanged();
        } else {
          dataListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder addDataList(
          int index, com.zzx.protoClasses.DbDataProto.DbData value) {
        if (dataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataListIsMutable();
          dataList_.add(index, value);
          onChanged();
        } else {
          dataListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder addDataList(
          com.zzx.protoClasses.DbDataProto.DbData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.add(builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder addDataList(
          int index, com.zzx.protoClasses.DbDataProto.DbData.Builder builderForValue) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder addAllDataList(
          java.lang.Iterable<? extends com.zzx.protoClasses.DbDataProto.DbData> values) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataList_);
          onChanged();
        } else {
          dataListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder clearDataList() {
        if (dataListBuilder_ == null) {
          dataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public Builder removeDataList(int index) {
        if (dataListBuilder_ == null) {
          ensureDataListIsMutable();
          dataList_.remove(index);
          onChanged();
        } else {
          dataListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public com.zzx.protoClasses.DbDataProto.DbData.Builder getDataListBuilder(
          int index) {
        return getDataListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public com.zzx.protoClasses.DbDataProto.DbDataOrBuilder getDataListOrBuilder(
          int index) {
        if (dataListBuilder_ == null) {
          return dataList_.get(index);  } else {
          return dataListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public java.util.List<? extends com.zzx.protoClasses.DbDataProto.DbDataOrBuilder> 
           getDataListOrBuilderList() {
        if (dataListBuilder_ != null) {
          return dataListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataList_);
        }
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public com.zzx.protoClasses.DbDataProto.DbData.Builder addDataListBuilder() {
        return getDataListFieldBuilder().addBuilder(
            com.zzx.protoClasses.DbDataProto.DbData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public com.zzx.protoClasses.DbDataProto.DbData.Builder addDataListBuilder(
          int index) {
        return getDataListFieldBuilder().addBuilder(
            index, com.zzx.protoClasses.DbDataProto.DbData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zzx.protoClasses.DbData data_list = 1;</code>
       */
      public java.util.List<com.zzx.protoClasses.DbDataProto.DbData.Builder> 
           getDataListBuilderList() {
        return getDataListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zzx.protoClasses.DbDataProto.DbData, com.zzx.protoClasses.DbDataProto.DbData.Builder, com.zzx.protoClasses.DbDataProto.DbDataOrBuilder> 
          getDataListFieldBuilder() {
        if (dataListBuilder_ == null) {
          dataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zzx.protoClasses.DbDataProto.DbData, com.zzx.protoClasses.DbDataProto.DbData.Builder, com.zzx.protoClasses.DbDataProto.DbDataOrBuilder>(
                  dataList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dataList_ = null;
        }
        return dataListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzx.protoClasses.DbDataList)
    }

    // @@protoc_insertion_point(class_scope:com.zzx.protoClasses.DbDataList)
    private static final com.zzx.protoClasses.DbDataProto.DbDataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzx.protoClasses.DbDataProto.DbDataList();
    }

    public static com.zzx.protoClasses.DbDataProto.DbDataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DbDataList>
        PARSER = new com.google.protobuf.AbstractParser<DbDataList>() {
      public DbDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DbDataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DbDataList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DbDataList> getParserForType() {
      return PARSER;
    }

    public com.zzx.protoClasses.DbDataProto.DbDataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzx_protoClasses_DbData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzx_protoClasses_DbData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzx_protoClasses_DbDataList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzx_protoClasses_DbDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014dbdata.proto\022\024com.zzx.protoClasses\"w\n\006" +
      "DbData\022\016\n\006gui_id\030\001 \002(\005\022\021\n\tdevice_id\030\002 \002(" +
      "\005\022\023\n\013device_name\030\003 \002(\t\022\022\n\ndevice_pos\030\004 \002" +
      "(\t\022\021\n\tdevice_ip\030\005 \002(\t\022\016\n\006module\030\006 \002(\t\"=\n" +
      "\nDbDataList\022/\n\tdata_list\030\001 \003(\0132\034.com.zzx" +
      ".protoClasses.DbDataB#\n\024com.zzx.protoCla" +
      "ssesB\013DbDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzx_protoClasses_DbData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzx_protoClasses_DbData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzx_protoClasses_DbData_descriptor,
        new java.lang.String[] { "GuiId", "DeviceId", "DeviceName", "DevicePos", "DeviceIp", "Module", });
    internal_static_com_zzx_protoClasses_DbDataList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zzx_protoClasses_DbDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzx_protoClasses_DbDataList_descriptor,
        new java.lang.String[] { "DataList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
